# version: '3'
version: '3.0'
services:
  frontend:
    # container_name: frontend
    # image: frontend
    container_name: 'frontend'
    image: 'frontend'
    security_opt:
      - seccomp=profile.json #Override the default labeling scheme for each container
    environment:
      - DISPLAY=host.docker.internal:0
    stdin_open: true #for keeping the containers open for interactive control
    ports: 
      - "3000:3000" #should probably fix, think we have only backend port which is 3001?
    networks:
      - spearmint
  backend:
    container_name: backend
    image: backend
    ports:
      - "3001:3001"
    networks:
      - spearmint
networks:
  spearmint:
    driver: bridge #specifies a logging driver for the service’s containers
